### ISSUE TITLE
0.2.1 not tagged

### ISSUE THREAD

**Issue by sjamaan** [0-8-15/pigeon-hole#1]
Hi there,

This egg's release-info file contains a reference to a "0.2.1" release, but there's no corresponding tag, so the URL `https://github.com/0-8-15/pigeon-hole/tarball/0.2.1` returns a 404. Could you please push a tag for 0.2.1, or remove the release from the release-info file?

Thanks!

**Comment by 0-8-15** [comment]
Done.

Remove old version.

Am Sun, 07 Jan 2018 10:59:45 +0000 (UTC)
schrieb Peter Bex <notifications@github.com>:

> Hi there,
> 
> This egg's release-info file contains a reference to a "0.2.1"
> release, but there's no corresponding tag, so the URL
> `https://github.com/0-8-15/pigeon-hole/tarball/0.2.1` returns a 404.
> Could you please push a tag for 0.2.1, or remove the release from the
> release-info file?
> 
> Thanks!
>
